# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        shell: bash
        run: |
          echo "version ${{inputs.environment}}"
          echo "env ${{vars.ENV}}"
